################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Doc_local/STMCUBE/x-cube-n6-ai-people-detection-tracking-main/Src/app.c \
C:/Doc_local/STMCUBE/x-cube-n6-ai-people-detection-tracking-main/Src/app_cam.c \
C:/Doc_local/STMCUBE/x-cube-n6-ai-people-detection-tracking-main/Src/app_fuseprogramming.c \
C:/Doc_local/STMCUBE/x-cube-n6-ai-people-detection-tracking-main/Src/freertos_bsp.c \
C:/Doc_local/STMCUBE/x-cube-n6-ai-people-detection-tracking-main/Src/main.c \
C:/Doc_local/STMCUBE/x-cube-n6-ai-people-detection-tracking-main/Src/stm32_lcd_ex.c \
C:/Doc_local/STMCUBE/x-cube-n6-ai-people-detection-tracking-main/Src/stm32n6xx_it.c \
C:/Doc_local/STMCUBE/x-cube-n6-ai-people-detection-tracking-main/Src/utils.c 

OBJS += \
./Src/app.o \
./Src/app_cam.o \
./Src/app_fuseprogramming.o \
./Src/freertos_bsp.o \
./Src/main.o \
./Src/stm32_lcd_ex.o \
./Src/stm32n6xx_it.o \
./Src/utils.o 

C_DEPS += \
./Src/app.d \
./Src/app_cam.d \
./Src/app_fuseprogramming.d \
./Src/freertos_bsp.d \
./Src/main.d \
./Src/stm32_lcd_ex.d \
./Src/stm32n6xx_it.d \
./Src/utils.d 


# Each subdirectory must supply rules for building sources it contributes
Src/app.o: C:/Doc_local/STMCUBE/x-cube-n6-ai-people-detection-tracking-main/Src/app.c Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_IMX335_SENSOR -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DSTM32N6570_NUCLEO_REV -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DSCR_LIB_USE_SPI -DSCR_LIB_USE_FREERTOS -c -I../../../../Inc -I../../../../Model/NUCLEO-N657X0-Q -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Lib/AI_Runtime/Inc -I../../../../Lib/AI_Runtime/Npu/ll_aton -I../../../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../../../Lib/ai-postprocessing-wrapper -I../../../../Lib/Camera_Middleware -I../../../../Lib/Camera_Middleware/sensors -I../../../../Lib/Camera_Middleware/sensors/imx335 -I../../../../Lib/Camera_Middleware/sensors/vd55g1 -I../../../../Lib/Camera_Middleware/sensors/vd6g -I../../../../Lib/Camera_Middleware/sensors/vd1943 -I../../../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../../../Lib/FreeRTOS/Source/include -I../../../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../../../Lib/screenl/Inc -I../../../../Lib/screenl/ili9341 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/app_cam.o: C:/Doc_local/STMCUBE/x-cube-n6-ai-people-detection-tracking-main/Src/app_cam.c Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_IMX335_SENSOR -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DSTM32N6570_NUCLEO_REV -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DSCR_LIB_USE_SPI -DSCR_LIB_USE_FREERTOS -c -I../../../../Inc -I../../../../Model/NUCLEO-N657X0-Q -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Lib/AI_Runtime/Inc -I../../../../Lib/AI_Runtime/Npu/ll_aton -I../../../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../../../Lib/ai-postprocessing-wrapper -I../../../../Lib/Camera_Middleware -I../../../../Lib/Camera_Middleware/sensors -I../../../../Lib/Camera_Middleware/sensors/imx335 -I../../../../Lib/Camera_Middleware/sensors/vd55g1 -I../../../../Lib/Camera_Middleware/sensors/vd6g -I../../../../Lib/Camera_Middleware/sensors/vd1943 -I../../../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../../../Lib/FreeRTOS/Source/include -I../../../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../../../Lib/screenl/Inc -I../../../../Lib/screenl/ili9341 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/app_fuseprogramming.o: C:/Doc_local/STMCUBE/x-cube-n6-ai-people-detection-tracking-main/Src/app_fuseprogramming.c Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_IMX335_SENSOR -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DSTM32N6570_NUCLEO_REV -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DSCR_LIB_USE_SPI -DSCR_LIB_USE_FREERTOS -c -I../../../../Inc -I../../../../Model/NUCLEO-N657X0-Q -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Lib/AI_Runtime/Inc -I../../../../Lib/AI_Runtime/Npu/ll_aton -I../../../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../../../Lib/ai-postprocessing-wrapper -I../../../../Lib/Camera_Middleware -I../../../../Lib/Camera_Middleware/sensors -I../../../../Lib/Camera_Middleware/sensors/imx335 -I../../../../Lib/Camera_Middleware/sensors/vd55g1 -I../../../../Lib/Camera_Middleware/sensors/vd6g -I../../../../Lib/Camera_Middleware/sensors/vd1943 -I../../../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../../../Lib/FreeRTOS/Source/include -I../../../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../../../Lib/screenl/Inc -I../../../../Lib/screenl/ili9341 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/freertos_bsp.o: C:/Doc_local/STMCUBE/x-cube-n6-ai-people-detection-tracking-main/Src/freertos_bsp.c Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_IMX335_SENSOR -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DSTM32N6570_NUCLEO_REV -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DSCR_LIB_USE_SPI -DSCR_LIB_USE_FREERTOS -c -I../../../../Inc -I../../../../Model/NUCLEO-N657X0-Q -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Lib/AI_Runtime/Inc -I../../../../Lib/AI_Runtime/Npu/ll_aton -I../../../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../../../Lib/ai-postprocessing-wrapper -I../../../../Lib/Camera_Middleware -I../../../../Lib/Camera_Middleware/sensors -I../../../../Lib/Camera_Middleware/sensors/imx335 -I../../../../Lib/Camera_Middleware/sensors/vd55g1 -I../../../../Lib/Camera_Middleware/sensors/vd6g -I../../../../Lib/Camera_Middleware/sensors/vd1943 -I../../../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../../../Lib/FreeRTOS/Source/include -I../../../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../../../Lib/screenl/Inc -I../../../../Lib/screenl/ili9341 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/main.o: C:/Doc_local/STMCUBE/x-cube-n6-ai-people-detection-tracking-main/Src/main.c Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_IMX335_SENSOR -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DSTM32N6570_NUCLEO_REV -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DSCR_LIB_USE_SPI -DSCR_LIB_USE_FREERTOS -c -I../../../../Inc -I../../../../Model/NUCLEO-N657X0-Q -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Lib/AI_Runtime/Inc -I../../../../Lib/AI_Runtime/Npu/ll_aton -I../../../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../../../Lib/ai-postprocessing-wrapper -I../../../../Lib/Camera_Middleware -I../../../../Lib/Camera_Middleware/sensors -I../../../../Lib/Camera_Middleware/sensors/imx335 -I../../../../Lib/Camera_Middleware/sensors/vd55g1 -I../../../../Lib/Camera_Middleware/sensors/vd6g -I../../../../Lib/Camera_Middleware/sensors/vd1943 -I../../../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../../../Lib/FreeRTOS/Source/include -I../../../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../../../Lib/screenl/Inc -I../../../../Lib/screenl/ili9341 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/stm32_lcd_ex.o: C:/Doc_local/STMCUBE/x-cube-n6-ai-people-detection-tracking-main/Src/stm32_lcd_ex.c Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_IMX335_SENSOR -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DSTM32N6570_NUCLEO_REV -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DSCR_LIB_USE_SPI -DSCR_LIB_USE_FREERTOS -c -I../../../../Inc -I../../../../Model/NUCLEO-N657X0-Q -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Lib/AI_Runtime/Inc -I../../../../Lib/AI_Runtime/Npu/ll_aton -I../../../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../../../Lib/ai-postprocessing-wrapper -I../../../../Lib/Camera_Middleware -I../../../../Lib/Camera_Middleware/sensors -I../../../../Lib/Camera_Middleware/sensors/imx335 -I../../../../Lib/Camera_Middleware/sensors/vd55g1 -I../../../../Lib/Camera_Middleware/sensors/vd6g -I../../../../Lib/Camera_Middleware/sensors/vd1943 -I../../../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../../../Lib/FreeRTOS/Source/include -I../../../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../../../Lib/screenl/Inc -I../../../../Lib/screenl/ili9341 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/stm32n6xx_it.o: C:/Doc_local/STMCUBE/x-cube-n6-ai-people-detection-tracking-main/Src/stm32n6xx_it.c Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_IMX335_SENSOR -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DSTM32N6570_NUCLEO_REV -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DSCR_LIB_USE_SPI -DSCR_LIB_USE_FREERTOS -c -I../../../../Inc -I../../../../Model/NUCLEO-N657X0-Q -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Lib/AI_Runtime/Inc -I../../../../Lib/AI_Runtime/Npu/ll_aton -I../../../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../../../Lib/ai-postprocessing-wrapper -I../../../../Lib/Camera_Middleware -I../../../../Lib/Camera_Middleware/sensors -I../../../../Lib/Camera_Middleware/sensors/imx335 -I../../../../Lib/Camera_Middleware/sensors/vd55g1 -I../../../../Lib/Camera_Middleware/sensors/vd6g -I../../../../Lib/Camera_Middleware/sensors/vd1943 -I../../../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../../../Lib/FreeRTOS/Source/include -I../../../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../../../Lib/screenl/Inc -I../../../../Lib/screenl/ili9341 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/utils.o: C:/Doc_local/STMCUBE/x-cube-n6-ai-people-detection-tracking-main/Src/utils.c Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_IMX335_SENSOR -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DSTM32N6570_NUCLEO_REV -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DSCR_LIB_USE_SPI -DSCR_LIB_USE_FREERTOS -c -I../../../../Inc -I../../../../Model/NUCLEO-N657X0-Q -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Lib/AI_Runtime/Inc -I../../../../Lib/AI_Runtime/Npu/ll_aton -I../../../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../../../Lib/ai-postprocessing-wrapper -I../../../../Lib/Camera_Middleware -I../../../../Lib/Camera_Middleware/sensors -I../../../../Lib/Camera_Middleware/sensors/imx335 -I../../../../Lib/Camera_Middleware/sensors/vd55g1 -I../../../../Lib/Camera_Middleware/sensors/vd6g -I../../../../Lib/Camera_Middleware/sensors/vd1943 -I../../../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../../../Lib/FreeRTOS/Source/include -I../../../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../../../Lib/screenl/Inc -I../../../../Lib/screenl/ili9341 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Src

clean-Src:
	-$(RM) ./Src/app.cyclo ./Src/app.d ./Src/app.o ./Src/app.su ./Src/app_cam.cyclo ./Src/app_cam.d ./Src/app_cam.o ./Src/app_cam.su ./Src/app_fuseprogramming.cyclo ./Src/app_fuseprogramming.d ./Src/app_fuseprogramming.o ./Src/app_fuseprogramming.su ./Src/freertos_bsp.cyclo ./Src/freertos_bsp.d ./Src/freertos_bsp.o ./Src/freertos_bsp.su ./Src/main.cyclo ./Src/main.d ./Src/main.o ./Src/main.su ./Src/stm32_lcd_ex.cyclo ./Src/stm32_lcd_ex.d ./Src/stm32_lcd_ex.o ./Src/stm32_lcd_ex.su ./Src/stm32n6xx_it.cyclo ./Src/stm32n6xx_it.d ./Src/stm32n6xx_it.o ./Src/stm32n6xx_it.su ./Src/utils.cyclo ./Src/utils.d ./Src/utils.o ./Src/utils.su

.PHONY: clean-Src

